---
- name: Налаштування веб-сервера Nginx
  hosts: webservers
  become: yes

  tasks:
    - name: Оновити кеш пакетів
      apt:
        update_cache: yes

    - name: Встановити Nginx
      apt:
        name: nginx
        state: present

    - name: Зупинити Apache2, якщо він запущений
      service:
        name: apache2
        state: stopped
        enabled: no
      ignore_errors: yes

    - name: Запустити Nginx та додати в автозавантаження
      service:
        name: nginx
        state: started
        enabled: yes
